-- ----------------------------------------------------------
-- MYSQL LO QUE DEBE CORRER EN LA BASE MYSQL
-- ----------------------------------------------------------
--
-- drop database galery;
-- create database galery;
-- use galery;
--
-- ------------------------------------------
-- -- -- TABLES
-- -- ---------------------------------------
-- CREATE TABLE Person (
--                         id VARCHAR(100) PRIMARY KEY,
--                         name VARCHAR(100) NOT NULL,
--                         country VARCHAR(100) NOT NULL,
--                         phone VARCHAR(50) NOT NULL,
--                         email VARCHAR(100) NOT NULL,
--                         last_name VARCHAR(100) NOT NULL
-- );
--
-- CREATE TABLE Institution (
--                              id VARCHAR(100) PRIMARY KEY,
--                              name VARCHAR(100) NOT NULL,
--                              country VARCHAR(100) NOT NULL,
--                              phone VARCHAR(50) NOT NULL,
--                              email VARCHAR(100) NOT NULL,
--                              website VARCHAR(100) NOT NULL
-- );
--
-- CREATE TABLE Reino (
--                        id VARCHAR(100) PRIMARY KEY,
--                        taxon_ancestor_id VARCHAR(100) NOT NULL,
--                        scientific_name VARCHAR(100) NOT NULL,
--                        author VARCHAR(50) NOT NULL,
--                        publication_year VARCHAR(100) NOT NULL
-- );
-- CREATE TABLE Division (
--                           id VARCHAR(100) PRIMARY KEY,
--                           taxon_ancestor_id VARCHAR(100) NOT NULL,
--                           scientific_name VARCHAR(100) NOT NULL,
--                           author VARCHAR(50) NOT NULL,
--                           publication_year VARCHAR(100) NOT NULL,
--                           FOREIGN KEY (taxon_ancestor_id) REFERENCES Reino(id)
-- );
-- CREATE TABLE Clase (
--                        id VARCHAR(100) PRIMARY KEY,
--                        taxon_ancestor_id VARCHAR(100) NOT NULL,
--                        scientific_name VARCHAR(100) NOT NULL,
--                        author VARCHAR(50) NOT NULL,
--                        publication_year VARCHAR(100) NOT NULL,
--                        FOREIGN KEY (taxon_ancestor_id) REFERENCES Division(id)
-- );
-- CREATE TABLE Orden (
--                        id VARCHAR(100) PRIMARY KEY,
--                        taxon_ancestor_id VARCHAR(100) NOT NULL,
--                        scientific_name VARCHAR(100) NOT NULL,
--                        author VARCHAR(50) NOT NULL,
--                        publication_year VARCHAR(100) NOT NULL,
--                        FOREIGN KEY (taxon_ancestor_id) REFERENCES Clase(id)
-- );
-- CREATE TABLE Familia (
--                          id VARCHAR(100) PRIMARY KEY,
--                          taxon_ancestor_id VARCHAR(100) NOT NULL,
--                          scientific_name VARCHAR(100) NOT NULL,
--                          author VARCHAR(50) NOT NULL,
--                          publication_year VARCHAR(100) NOT NULL,
--                          FOREIGN KEY (taxon_ancestor_id) REFERENCES Orden(id)
-- );
-- CREATE TABLE Genero (
--                         id VARCHAR(100) PRIMARY KEY,
--                         taxon_ancestor_id VARCHAR(100) NOT NULL,
--                         scientific_name VARCHAR(100) NOT NULL,
--                         author VARCHAR(50) NOT NULL,
--                         publication_year VARCHAR(100) NOT NULL,
--                         FOREIGN KEY (taxon_ancestor_id) REFERENCES Familia(id)
-- );
-- CREATE TABLE Especie (
--                          id VARCHAR(100) PRIMARY KEY,
--                          taxon_ancestor_id VARCHAR(100) NOT NULL,
--                          scientific_name VARCHAR(100) NOT NULL,
--                          author VARCHAR(50) NOT NULL,
--                          publication_year VARCHAR(100) NOT NULL,
--                          FOREIGN KEY (taxon_ancestor_id) REFERENCES Genero(id)
-- );
--
--
-- CREATE TABLE image (
--                        id VARCHAR(100) PRIMARY KEY,
--                        description VARCHAR(500) NOT NULL,
--                        url VARCHAR(500) NOT NULL,
--                        upload_date TIMESTAMP not null DEFAULT NOW(),
--                        keywords VARCHAR(500),
--                        author_id VARCHAR(100) NOT NULL,
--                        owner_id VARCHAR(100) NOT NULL,
--                        license ENUM('CC BY', 'CC BY-SA', 'CC BY-ND', 'CC BY-NC', 'CC BY-NC-SA', 'CC BY-NC-ND') NOT NULL,
--                        taxon_id VARCHAR(100) NOT NULL,
--                        FOREIGN KEY (author_id) REFERENCES Person(id),
--                        FOREIGN KEY (owner_id) REFERENCES Institution(id)
-- );
--
-- -----------------------------------------
-- -- -- PROCEDURES
-- -- ---------------------------------------
-- delimiter //
-- CREATE PROCEDURE searchByKeyWords(IN buscar VARCHAR(225))
-- BEGIN
-- SELECT *
-- FROM image
-- WHERE
--         author_id = (
--         SELECT id
--         FROM Person
--         WHERE name LIKE CONCAT('%', buscar, '%')
--     )
--    OR
--         owner_id =(
--         SELECT id
--         FROM Institution
--         WHERE name LIKE CONCAT('%', buscar, '%')
--     )
--    OR
--         taxon_id =(
--         SELECT id
--         FROM Reino
--         WHERE scientific_name LIKE CONCAT('%', buscar, '%')
--     )
--    OR
--         taxon_id =(
--         SELECT id
--         FROM Orden
--         WHERE scientific_name LIKE CONCAT('%', buscar, '%')
--     )
--    OR
--         taxon_id =(
--         SELECT id
--         FROM Genero
--         WHERE scientific_name LIKE CONCAT('%', buscar, '%')
--     )
--    OR
--         taxon_id =(
--         SELECT id
--         FROM Familia
--         WHERE scientific_name LIKE CONCAT('%', buscar, '%')
--     )
--    OR
--         taxon_id =(
--         SELECT id
--         FROM Especie
--         WHERE scientific_name LIKE CONCAT('%', buscar, '%')
--     )
--    OR
--         taxon_id =(
--         SELECT id
--         FROM Division
--         WHERE scientific_name LIKE CONCAT('%', buscar, '%')
--     )
--    OR
--         taxon_id =(
--         SELECT id
--         FROM Clase
--         WHERE scientific_name LIKE CONCAT('%', buscar, '%')
--     )
--    OR
--         keywords LIKE CONCAT('%', buscar, '%');
-- END //
--
--
-- --------------------------------- --------
-- -- -- Inserts
-- -- ---------------------------------------
-- INSERT INTO Institution (id, name, country, phone, email, website)
-- VALUES ('456', 'TEC', 'CR', '+34 123456789', 'TEC@example.com', 'TEC.com');
--
-- INSERT INTO Institution (id, name, country, phone, email, website)
-- VALUES ('457', 'UTN', 'CR', '+34 222222222', 'UTN@example.com', 'UTN.com');
--
-- INSERT INTO Person (id, name, country, phone, email, last_name)
-- VALUES ('123', 'Juan', 'Spain', '+34 123888788', 'juan@example.com', 'Pérez');
--
-- INSERT INTO Person (id, name, country, phone, email, last_name)
-- VALUES ('124', 'Isaac', 'CR', '+34 55555555', 'isaac@example.com', 'Melendez');
--
-- -- ------------------------------------------------------------------------------------
--
-- INSERT INTO Reino (id, taxon_ancestor_id, scientific_name, author, publication_year)
-- VALUES ('1', '0', 'Animalia', 'Carl Linnaeus', '1758-05-03');
--
-- INSERT INTO Reino (id, taxon_ancestor_id, scientific_name, author, publication_year)
-- VALUES ('2', '0', 'Plantae', 'Carl Linnaeus', '1758-05-03');
--
-- INSERT INTO Division (id, taxon_ancestor_id, scientific_name, author, publication_year)
-- VALUES ('2', '1', 'Chordata', 'Valentine', '1995-05-03');
--
-- INSERT INTO Clase (id, taxon_ancestor_id, scientific_name, author, publication_year)
-- VALUES ('3', '2', 'Mammalia', 'Linnaeus', '1758-05-03');
--
-- INSERT INTO Orden (id, taxon_ancestor_id, scientific_name, author, publication_year)
-- VALUES ('4', '3', 'Carnivora', 'Bowdich', '1821-05-03');
--
-- INSERT INTO Familia (id, taxon_ancestor_id, scientific_name, author, publication_year)
-- VALUES ('5', '4', 'Felidae', 'Fischer de Waldheim', '1817-05-03');
--
-- INSERT INTO Genero (id, taxon_ancestor_id, scientific_name, author, publication_year)
-- VALUES ('6', '5', 'Panthera', 'Oken', '1816-05-03');
--
-- INSERT INTO Especie (id, taxon_ancestor_id, scientific_name, author, publication_year)
-- VALUES ('7', '6', 'Panthera leo', 'Linnaeus', '1758-05-03');
--
--
-- -- ------------------------------------------------------------------------------------
--
-- INSERT INTO image (id, description, url, keywords, author_id, owner_id, license, taxon_id)
-- VALUES ('1001', 'Colibri con una flor', 'https://firebasestorage.googleapis.com/v0/b/galery-react.appspot.com/o/1683072326655-colibri.png?alt=media&token=a05152a8-527b-436f-8324-e92f115b4d8e'
--        , 'colibri, flor, naturaleza', '123', '456', 'CC BY-SA', 'Animalia');
--
-- INSERT INTO image (id, description, url, keywords, author_id, owner_id, license, taxon_id)
-- VALUES ('1002', 'Perezoso en un arbol', 'https://firebasestorage.googleapis.com/v0/b/galery-react.appspot.com/o/1683075707343-perezoso.jpg?alt=media&token=19ab7c29-32b1-4503-8cb4-9c75526fec10'
--        , 'Perezoso, arbol, naturaleza', '123', '456', 'CC BY-ND', 'Animalia');
--
-- INSERT INTO image (id, description, url, keywords, author_id, owner_id, license, taxon_id)
-- VALUES ('1003', 'arbol de guanacaste', 'https://firebasestorage.googleapis.com/v0/b/galery-react.appspot.com/o/1683078529877-arbol_de_guancaste.jpg?alt=media&token=5e89d1dc-eb31-4573-8258-d7958813fbf1'
--        , 'arbol, guanacaste', '124', '457', 'CC BY-NC-SA', 'Plantae');
--
-- INSERT INTO image (id, description, url, keywords, author_id, owner_id, license, taxon_id)
-- VALUES ('1004', 'Elefante adulto', 'https://firebasestorage.googleapis.com/v0/b/galery-react.appspot.com/o/1683079023668-elefantes.jpg?alt=media&token=f9029126-366d-4f87-8f62-504c0b993563'
--        , 'elefante', '124', '456', 'CC BY-NC-SA', 'Animalia');
--
-- INSERT INTO image (id, description, url, keywords, author_id, owner_id, license, taxon_id)
-- VALUES ('1005', 'Iguana verde', 'https://firebasestorage.googleapis.com/v0/b/galery-react.appspot.com/o/1683079208085-iguana.jpg?alt=media&token=a4e94465-a0ac-409d-bb02-29b5c55fc614'
--        , 'iguana, verde', '124', '456', 'CC BY-NC-SA', 'Animalia');
--
-- INSERT INTO image (id, description, url, keywords, author_id, owner_id, license, taxon_id)
-- VALUES ('1006', 'Tiburon en el agua', 'https://firebasestorage.googleapis.com/v0/b/galery-react.appspot.com/o/1683079332617-tiburon.jpg?alt=media&token=f4501a7d-9908-4a69-bbc6-e50c6907da68'
--        , 'Tiburon, agua, grande', '123', '456', 'CC BY-NC-SA', 'Animalia');
--
-- INSERT INTO image (id, description, url, keywords, author_id, owner_id, license, taxon_id)
-- VALUES ('1007', 'Girasol', 'https://firebasestorage.googleapis.com/v0/b/galery-react.appspot.com/o/1683079513417-girasol.jpg?alt=media&token=96c126ab-13a3-4f22-be96-13652d158534'
--        , 'Girasol, amarillo, flor', '123', '456', 'CC BY-ND', 'Plantae');
--
-- INSERT INTO image (id, description, url, keywords, author_id, owner_id, license, taxon_id)
-- VALUES ('1008', 'Delfin en el agua', 'https://firebasestorage.googleapis.com/v0/b/galery-react.appspot.com/o/1683079939838-delfin.jpg?alt=media&token=76974de8-d2f5-4ca6-9bd8-a84581e63912'
--        , 'delfin, agua', '123', '457', 'CC BY-ND', 'Animalia');
--
